CREATE TABLE Users
(
    Id INT IDENTITY,
    FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    Email_Confirmed BIT NOT NULL CONSTRAINT DF_User_Email_Confirmed DEFAULT 0,
	Password NVARCHAR(100) NOT NULL,
	Role_Id INT NOT NULL,
	Blocked BIT NOT NULL CONSTRAINT DF_User_Blocked DEFAULT 0,
	Image VARCHAR(MAX),
	Image_Name NVARCHAR(1000),

CONSTRAINT PK_Users_Id PRIMARY KEY (Id),
CONSTRAINT UQ_Users_Email UNIQUE (Email),
CONSTRAINT FK_Users_To_Roles FOREIGN KEY (Role_Id)  REFERENCES Roles (Id)
)
