//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithMentorDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_PLAN_TASK
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Mod_Date { get; set; }
        public bool Published { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Section_Name { get; set; }
        public string Task_Name { get; set; }
        public string Task_Description { get; set; }
        public Nullable<System.DateTime> Tasks_Create_Date { get; set; }
        public Nullable<System.DateTime> Task_Mod_Date { get; set; }
        public bool Private { get; set; }
    }
}
