//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithMentorDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int UserTask_Id { get; set; }
        public int User_Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
    
        public virtual User Creator { get; set; }
        public virtual UserTask UserTask { get; set; }
    }
}
