//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithMentorDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSuggestion
    {
        public int Plan_Id { get; set; }
        public int User_Id { get; set; }
        public int Mentor_Id { get; set; }
        public string Text { get; set; }
    
        public virtual Plan Plans { get; set; }
        public virtual User Users { get; set; }
        public virtual User Users1 { get; set; }
    }
}
