//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWithMentorDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTask()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int PlanTask_Id { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Propose_End_Date { get; set; }
        public int Mentor_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual PlanTask PlanTask { get; set; }
        public virtual User Mentor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
