
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'comments' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.comments")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'groupPlanTaskView' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.groupPlanTaskView")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'groups' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.groups")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'messages' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.messages")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'plans' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.plans")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'planSuggestions' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.planSuggestions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'planTasks' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.planTasks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'roles' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.roles")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'sections' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.sections")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'tasks' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.tasks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'userRoleView' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.userRoleView")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'users' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.users")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1450:Remove the field 'userTasks' and declare it as a local variable in the relevant methods.", Justification = "<Ожидание>", Scope = "member", Target = "~F:LearnWithMentorDAL.UnitOfWork.UnitOfWork.userTasks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S2245:Make sure that using this pseudorandom number generator is safe here.", Justification = "<Ожидание>", Scope = "member", Target = "~M:LearnWithMentorDAL.EF.LearnWithMentorInitializer.InitializeComments(LearnWithMentorDAL.Entities.LearnWithMentor_DBEntities)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S2245:Make sure that using this pseudorandom number generator is safe here.", Justification = "<Ожидание>", Scope = "member", Target = "~M:LearnWithMentorDAL.EF.LearnWithMentorInitializer.InitializeMessages(LearnWithMentorDAL.Entities.LearnWithMentor_DBEntities)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S3881:Fix this implementation of 'IDisposable' to conform to the dispose pattern.", Justification = "<Ожидание>", Scope = "type", Target = "~T:LearnWithMentorDAL.UnitOfWork.UnitOfWork")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "LearnWithMentorDAL.UnitOfWork.UnitOfWork.#Dispose(System.Boolean)")]

